language: python
python:
  - '2.6'
  - '2.7'
  - '3.2'
  - '3.3'
install:
  - pip install --use-mirrors cram
  - python setup.py -q install
script:
  - python setup.py test
  - cram django_future_url/test/cram

